/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.syslib;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
/**
 *
 * @author engenheiro
 */
public class CatalogoScreen extends javax.swing.JPanel {

    /**
     * Creates new form Form1
     */
    public CatalogoScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name2 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        contentArea = new javax.swing.JPanel();
        booksLabel = new javax.swing.JLabel();
        book1 = new javax.swing.JLabel();
        myBooksLabel = new javax.swing.JLabel();
        book2 = new javax.swing.JLabel();
        recentBooksLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));

        name2.setBackground(new java.awt.Color(62, 67, 159));
        name2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("Syslib");
        name2.setToolTipText("");
        name2.setOpaque(true);

        contentArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));

        booksLabel.setText("Livros");

        book1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image1.png"))); // NOI18N

        myBooksLabel.setText("Meus Livros");

        book2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image2.png"))); // NOI18N

        recentBooksLabel.setText("Livros recentes");

        javax.swing.GroupLayout contentAreaLayout = new javax.swing.GroupLayout(contentArea);
        contentArea.setLayout(contentAreaLayout);
        contentAreaLayout.setHorizontalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentAreaLayout.createSequentialGroup()
                        .addComponent(book1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(book2))
                    .addComponent(myBooksLabel)
                    .addComponent(recentBooksLabel)
                    .addComponent(booksLabel))
                .addContainerGap(696, Short.MAX_VALUE))
        );
        contentAreaLayout.setVerticalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(myBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(book1)
                    .addComponent(book2))
                .addGap(18, 18, 18)
                .addComponent(recentBooksLabel)
                .addGap(252, 252, 252)
                .addComponent(booksLabel)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        ScrollPane.setViewportView(contentArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel book1;
    private javax.swing.JLabel book2;
    private javax.swing.JLabel booksLabel;
    private javax.swing.JPanel contentArea;
    private javax.swing.JLabel myBooksLabel;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel recentBooksLabel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JScrollPane test = new JScrollPane(
        contentArea, 
        JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
    );
}
