/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.syslib;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author engenheiro
 */
public class NewFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
        
        // Rolagem rapida
        this.ScrollPane.getVerticalScrollBar().setUnitIncrement(30);
        // Janela no meio da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        loginScreen = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        contentArea = new javax.swing.JPanel();
        loginContent = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        buttonEsqueciSenha = new javax.swing.JLabel();
        buttonSouBibliotecario = new javax.swing.JLabel();
        catalogoScreen = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnSearchBarLabel = new javax.swing.JLabel();
        btnMenuLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        contentArea1 = new javax.swing.JPanel();
        booksLabel = new javax.swing.JLabel();
        myBooksLabel = new javax.swing.JLabel();
        recentBooksLabel = new javax.swing.JLabel();
        bookImage1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MenuScreen = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        contentArea2 = new javax.swing.JPanel();
        menuContent = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        settingsButton1 = new javax.swing.JButton();
        settingsButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BookScreen = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        contentArea3 = new javax.swing.JPanel();
        bookImage = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JPanel();
        deadLineLabel = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        messageContainer = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        RegisterBookScreen = new javax.swing.JPanel();
        name4 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JLabel();
        contentArea4 = new javax.swing.JPanel();
        registerBookContent = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        authorLabel1 = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        publicationDateLabel = new javax.swing.JLabel();
        publicationDateTextField = new javax.swing.JTextField();
        publishingCompanyLabel = new javax.swing.JLabel();
        publishingCompanyTextField = new javax.swing.JTextField();
        addImageButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        RegisterUserScreen = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        contentArea5 = new javax.swing.JPanel();
        registerUserContent = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField1 = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        institutionLabel = new javax.swing.JLabel();
        institutionTextField = new javax.swing.JTextField();
        registerButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UsersScreen = new javax.swing.JPanel();
        name6 = new javax.swing.JLabel();
        searchBarContent = new javax.swing.JPanel();
        backButton2 = new javax.swing.JLabel();
        searchBarLabel = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usersContent = new javax.swing.JPanel();
        userContent1 = new javax.swing.JPanel();
        userImageLabel = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        numberOfBooksLabel = new javax.swing.JLabel();
        deleteImageLabel = new javax.swing.JLabel();
        userContent3 = new javax.swing.JPanel();
        userImageLabel2 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        numberOfBooksLabel1 = new javax.swing.JLabel();
        deleteImageLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(new java.awt.CardLayout());

        loginScreen.setBackground(new java.awt.Color(243, 243, 243));

        name1.setBackground(new java.awt.Color(62, 67, 159));
        name1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Syslib");
        name1.setToolTipText("");
        name1.setOpaque(true);

        loginContent.setBackground(new java.awt.Color(217, 217, 217));
        loginContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Faça seu login para continuar");
        title.setToolTipText("");

        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        loginButton.setLabel("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        buttonEsqueciSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonEsqueciSenha.setText("Esqueci a senha");

        buttonSouBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSouBibliotecario.setText("Sou bibliotecário(a)");

        javax.swing.GroupLayout loginContentLayout = new javax.swing.GroupLayout(loginContent);
        loginContent.setLayout(loginContentLayout);
        loginContentLayout.setHorizontalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonSouBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginContentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        loginContentLayout.setVerticalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title)
                .addGap(29, 29, 29)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSouBibliotecario)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentAreaLayout = new javax.swing.GroupLayout(contentArea);
        contentArea.setLayout(contentAreaLayout);
        contentAreaLayout.setHorizontalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(loginContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        contentAreaLayout.setVerticalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(loginContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        backgroundPanel.add(loginScreen, "card3");

        catalogoScreen.setBackground(new java.awt.Color(243, 243, 243));

        name2.setBackground(new java.awt.Color(62, 67, 159));
        name2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("Syslib");
        name2.setToolTipText("");
        name2.setOpaque(true);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnSearchBarLabel.setText("O que você quer ler hoje?");
        btnSearchBarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchBarLabelMouseClicked(evt);
            }
        });

        btnMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuLabelMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuLabel)
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearchBarLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnSearchBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(btnMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contentArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        booksLabel.setText("Livros");

        myBooksLabel.setText("Meus Livros");

        recentBooksLabel.setText("Livros recentes");

        bookImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image1.png"))); // NOI18N
        bookImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookImage1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image2.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image2.png"))); // NOI18N

        javax.swing.GroupLayout contentArea1Layout = new javax.swing.GroupLayout(contentArea1);
        contentArea1.setLayout(contentArea1Layout);
        contentArea1Layout.setHorizontalGroup(
            contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recentBooksLabel)
                    .addComponent(booksLabel)
                    .addComponent(myBooksLabel)
                    .addComponent(bookImage1)
                    .addGroup(contentArea1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(contentArea1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(962, Short.MAX_VALUE))
        );
        contentArea1Layout.setVerticalGroup(
            contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(myBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookImage1)
                .addGap(18, 18, 18)
                .addComponent(recentBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(booksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(1049, Short.MAX_VALUE))
        );

        ScrollPane.setViewportView(contentArea1);

        javax.swing.GroupLayout catalogoScreenLayout = new javax.swing.GroupLayout(catalogoScreen);
        catalogoScreen.setLayout(catalogoScreenLayout);
        catalogoScreenLayout.setHorizontalGroup(
            catalogoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(catalogoScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catalogoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        catalogoScreenLayout.setVerticalGroup(
            catalogoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoScreenLayout.createSequentialGroup()
                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundPanel.add(catalogoScreen, "card4");

        name3.setBackground(new java.awt.Color(62, 67, 159));
        name3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setText("Syslib");
        name3.setToolTipText("");
        name3.setOpaque(true);

        menuContent.setBackground(new java.awt.Color(217, 217, 217));
        menuContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        title1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Menu");
        title1.setToolTipText("");

        settingsButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        settingsButton.setText("Livros");
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        logoutButton.setText("Sair");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        settingsButton1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        settingsButton1.setText("Configurações");
        settingsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButton1ActionPerformed(evt);
            }
        });

        settingsButton2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        settingsButton2.setText("Usuários");
        settingsButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButton2MouseClicked(evt);
            }
        });
        settingsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuContentLayout = new javax.swing.GroupLayout(menuContent);
        menuContent.setLayout(menuContentLayout);
        menuContentLayout.setHorizontalGroup(
            menuContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuContentLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(menuContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        menuContentLayout.setVerticalGroup(
            menuContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel8.setText("Voltar");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentArea2Layout = new javax.swing.GroupLayout(contentArea2);
        contentArea2.setLayout(contentArea2Layout);
        contentArea2Layout.setHorizontalGroup(
            contentArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea2Layout.createSequentialGroup()
                .addGroup(contentArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentArea2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(menuContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentArea2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        contentArea2Layout.setVerticalGroup(
            contentArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(86, 86, 86)
                .addComponent(menuContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuScreenLayout = new javax.swing.GroupLayout(MenuScreen);
        MenuScreen.setLayout(MenuScreenLayout);
        MenuScreenLayout.setHorizontalGroup(
            MenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentArea2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuScreenLayout.setVerticalGroup(
            MenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuScreenLayout.createSequentialGroup()
                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentArea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        backgroundPanel.add(MenuScreen, "card4");

        name.setBackground(new java.awt.Color(62, 67, 159));
        name.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Syslib");
        name.setToolTipText("");
        name.setOpaque(true);

        backButton.setText("Voltar");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        bookImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baseBook.png"))); // NOI18N

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Título do livro");

        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel.setText("Autor do livro");

        deadLineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadLineLabel.setText("Data de devolução: 22/10/2001");

        bookButton.setText("Reservar");

        javax.swing.GroupLayout buttonContainerLayout = new javax.swing.GroupLayout(buttonContainer);
        buttonContainer.setLayout(buttonContainerLayout);
        buttonContainerLayout.setHorizontalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deadLineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(445, 445, 445))
        );
        buttonContainerLayout.setVerticalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonContainerLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(deadLineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookButton)
                .addGap(9, 9, 9))
        );

        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Seu livro foi reservado! Compareça a biblioteca para retirar seu exemplar!");

        javax.swing.GroupLayout messageContainerLayout = new javax.swing.GroupLayout(messageContainer);
        messageContainer.setLayout(messageContainerLayout);
        messageContainerLayout.setHorizontalGroup(
            messageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageContainerLayout.createSequentialGroup()
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        messageContainerLayout.setVerticalGroup(
            messageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentArea3Layout = new javax.swing.GroupLayout(contentArea3);
        contentArea3.setLayout(contentArea3Layout);
        contentArea3Layout.setHorizontalGroup(
            contentArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
            .addComponent(buttonContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(messageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentArea3Layout.setVerticalGroup(
            contentArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentArea3Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(bookImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(authorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BookScreenLayout = new javax.swing.GroupLayout(BookScreen);
        BookScreen.setLayout(BookScreenLayout);
        BookScreenLayout.setHorizontalGroup(
            BookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(BookScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookScreenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contentArea3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        BookScreenLayout.setVerticalGroup(
            BookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookScreenLayout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(533, Short.MAX_VALUE))
            .addGroup(BookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentArea3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(BookScreen, "card5");

        name4.setBackground(new java.awt.Color(62, 67, 159));
        name4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("Syslib");
        name4.setToolTipText("");
        name4.setOpaque(true);

        backButton1.setText("Voltar");
        backButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton1MouseClicked(evt);
            }
        });

        registerBookContent.setBackground(new java.awt.Color(217, 217, 217));
        registerBookContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        title2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Cadastro de livro");
        title2.setToolTipText("");

        nameLabel.setText("Nome");

        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        authorLabel1.setText("Autor");

        authorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTextFieldActionPerformed(evt);
            }
        });

        publicationDateLabel.setText("Data de publicação");

        publicationDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationDateTextFieldActionPerformed(evt);
            }
        });

        publishingCompanyLabel.setText("Editora");

        publishingCompanyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishingCompanyTextFieldActionPerformed(evt);
            }
        });

        addImageButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        addImageButton.setText("Adicionar Imagem");
        addImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        registerButton.setText("Cadastrar");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerBookContentLayout = new javax.swing.GroupLayout(registerBookContent);
        registerBookContent.setLayout(registerBookContentLayout);
        registerBookContentLayout.setHorizontalGroup(
            registerBookContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(registerBookContentLayout.createSequentialGroup()
                .addGroup(registerBookContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerBookContentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(registerBookContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publishingCompanyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publishingCompanyLabel)
                            .addComponent(authorLabel1)
                            .addComponent(publicationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publicationDateLabel)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerBookContentLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(addImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerBookContentLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        registerBookContentLayout.setVerticalGroup(
            registerBookContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerBookContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLabel1)
                .addGap(5, 5, 5)
                .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publicationDateLabel)
                .addGap(5, 5, 5)
                .addComponent(publicationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publishingCompanyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publishingCompanyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentArea4Layout = new javax.swing.GroupLayout(contentArea4);
        contentArea4.setLayout(contentArea4Layout);
        contentArea4Layout.setHorizontalGroup(
            contentArea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(registerBookContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        contentArea4Layout.setVerticalGroup(
            contentArea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentArea4Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(registerBookContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RegisterBookScreenLayout = new javax.swing.GroupLayout(RegisterBookScreen);
        RegisterBookScreen.setLayout(RegisterBookScreenLayout);
        RegisterBookScreenLayout.setHorizontalGroup(
            RegisterBookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterBookScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(contentArea4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterBookScreenLayout.setVerticalGroup(
            RegisterBookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBookScreenLayout.createSequentialGroup()
                .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterBookScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentArea4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        backgroundPanel.add(RegisterBookScreen, "card6");

        name5.setBackground(new java.awt.Color(62, 67, 159));
        name5.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name5.setForeground(new java.awt.Color(255, 255, 255));
        name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name5.setText("Syslib");
        name5.setToolTipText("");
        name5.setOpaque(true);

        registerUserContent.setBackground(new java.awt.Color(217, 217, 217));
        registerUserContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        title3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Cadastro de usuário");
        title3.setToolTipText("");

        nameLabel1.setText("Nome");

        nameTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField1ActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");

        emailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField1ActionPerformed(evt);
            }
        });

        cpfLabel.setText("CPF");

        cpfTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextField1ActionPerformed(evt);
            }
        });

        genderLabel.setText("Gênero");

        genderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextFieldActionPerformed(evt);
            }
        });

        institutionLabel.setText("Instituição de ensino");

        institutionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institutionTextFieldActionPerformed(evt);
            }
        });

        registerButton1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        registerButton1.setText("Cadastrar");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerUserContentLayout = new javax.swing.GroupLayout(registerUserContent);
        registerUserContent.setLayout(registerUserContentLayout);
        registerUserContentLayout.setHorizontalGroup(
            registerUserContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(registerUserContentLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(registerUserContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel)
                    .addComponent(emailLabel)
                    .addComponent(cpfTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(nameLabel1)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(institutionLabel)
                    .addComponent(institutionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerUserContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        registerUserContentLayout.setVerticalGroup(
            registerUserContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel)
                .addGap(5, 5, 5)
                .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfLabel)
                .addGap(5, 5, 5)
                .addComponent(cpfTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(institutionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(institutionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel7.setText("Voltar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentArea5Layout = new javax.swing.GroupLayout(contentArea5);
        contentArea5.setLayout(contentArea5Layout);
        contentArea5Layout.setHorizontalGroup(
            contentArea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea5Layout.createSequentialGroup()
                .addGroup(contentArea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentArea5Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(registerUserContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentArea5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        contentArea5Layout.setVerticalGroup(
            contentArea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerUserContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterUserScreenLayout = new javax.swing.GroupLayout(RegisterUserScreen);
        RegisterUserScreen.setLayout(RegisterUserScreenLayout);
        RegisterUserScreenLayout.setHorizontalGroup(
            RegisterUserScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentArea5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegisterUserScreenLayout.setVerticalGroup(
            RegisterUserScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterUserScreenLayout.createSequentialGroup()
                .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentArea5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        backgroundPanel.add(RegisterUserScreen, "card7");

        name6.setBackground(new java.awt.Color(62, 67, 159));
        name6.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name6.setForeground(new java.awt.Color(255, 255, 255));
        name6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name6.setText("Syslib");
        name6.setToolTipText("");
        name6.setOpaque(true);

        backButton2.setText("Voltar");
        backButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton2MouseClicked(evt);
            }
        });

        searchBarLabel.setText("Qual usuário deseja buscar?");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchBarContentLayout = new javax.swing.GroupLayout(searchBarContent);
        searchBarContent.setLayout(searchBarContentLayout);
        searchBarContentLayout.setHorizontalGroup(
            searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBarLabel)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );
        searchBarContentLayout.setVerticalGroup(
            searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarContentLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(searchBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton2)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );

        userImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        nameLabel2.setText("Daniel Alencar Penha Carvalho");

        numberOfBooksLabel.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        numberOfBooksLabel.setText("18");

        deleteImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N

        javax.swing.GroupLayout userContent1Layout = new javax.swing.GroupLayout(userContent1);
        userContent1.setLayout(userContent1Layout);
        userContent1Layout.setHorizontalGroup(
            userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userContent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userImageLabel)
                .addGap(18, 18, 18)
                .addComponent(nameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(numberOfBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteImageLabel)
                .addGap(12, 12, 12))
        );
        userContent1Layout.setVerticalGroup(
            userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                        .addComponent(userImageLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                        .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteImageLabel)
                            .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameLabel2)
                                .addComponent(numberOfBooksLabel)))
                        .addGap(18, 18, 18))))
        );

        userImageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        nameLabel4.setText("Daniel Alencar Penha Carvalho");

        numberOfBooksLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        numberOfBooksLabel1.setText("18");

        deleteImageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N

        javax.swing.GroupLayout userContent3Layout = new javax.swing.GroupLayout(userContent3);
        userContent3.setLayout(userContent3Layout);
        userContent3Layout.setHorizontalGroup(
            userContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userContent3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userImageLabel2)
                .addGap(18, 18, 18)
                .addComponent(nameLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberOfBooksLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteImageLabel2)
                .addGap(12, 12, 12))
        );
        userContent3Layout.setVerticalGroup(
            userContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent3Layout.createSequentialGroup()
                        .addComponent(userImageLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent3Layout.createSequentialGroup()
                        .addGroup(userContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteImageLabel2)
                            .addGroup(userContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameLabel4)
                                .addComponent(numberOfBooksLabel1)))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout usersContentLayout = new javax.swing.GroupLayout(usersContent);
        usersContent.setLayout(usersContentLayout);
        usersContentLayout.setHorizontalGroup(
            usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userContent3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(usersContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        usersContentLayout.setVerticalGroup(
            usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersContentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(userContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UsersScreenLayout = new javax.swing.GroupLayout(UsersScreen);
        UsersScreen.setLayout(UsersScreenLayout);
        UsersScreenLayout.setHorizontalGroup(
            UsersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(UsersScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBarContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(UsersScreenLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(usersContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsersScreenLayout.setVerticalGroup(
            UsersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersScreenLayout.createSequentialGroup()
                .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBarContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundPanel.add(UsersScreen, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
        loginScreen.setVisible(false);
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuLabelMouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        loginScreen.setVisible(false);
        BookScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        
        MenuScreen.setVisible(true);
    }//GEN-LAST:event_btnMenuLabelMouseClicked

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnSearchBarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBarLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBarLabelMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        MenuScreen.setVisible(false);
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        
        loginScreen.setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void bookImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookImage1MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        
        BookScreen.setVisible(true);
    }//GEN-LAST:event_bookImage1MouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void settingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButton1ActionPerformed

    private void settingsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        
        RegisterBookScreen.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void authorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTextFieldActionPerformed

    private void publicationDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publicationDateTextFieldActionPerformed

    private void publishingCompanyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishingCompanyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishingCompanyTextFieldActionPerformed

    private void addImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addImageButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void backButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton1MouseClicked
        // TODO add your handling code here:
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_backButton1MouseClicked

    private void nameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField1ActionPerformed

    private void emailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1ActionPerformed

    private void cpfTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextField1ActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void institutionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institutionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_institutionTextFieldActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void backButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton2MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        MenuScreen.setVisible(true);
    }//GEN-LAST:event_backButton2MouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void settingsButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButton2MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        UsersScreen.setVisible(true);
    }//GEN-LAST:event_settingsButton2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        RegisterUserScreen.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        MenuScreen.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        catalogoScreen.setVisible(false);
        BookScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        BookScreen.setVisible(false);
        MenuScreen.setVisible(false);
        RegisterUserScreen.setVisible(false);
        UsersScreen.setVisible(false);
        loginScreen.setVisible(false);
        RegisterBookScreen.setVisible(false);
        
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_settingsButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookScreen;
    private javax.swing.JPanel MenuScreen;
    private javax.swing.JPanel RegisterBookScreen;
    private javax.swing.JPanel RegisterUserScreen;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JPanel UsersScreen;
    private javax.swing.JButton addImageButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorLabel1;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel backButton1;
    private javax.swing.JLabel backButton2;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton bookButton;
    private javax.swing.JLabel bookImage;
    private javax.swing.JLabel bookImage1;
    private javax.swing.JLabel booksLabel;
    private javax.swing.JLabel btnMenuLabel;
    private javax.swing.JLabel btnSearchBarLabel;
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JLabel buttonEsqueciSenha;
    private javax.swing.JLabel buttonSouBibliotecario;
    private javax.swing.JPanel catalogoScreen;
    private javax.swing.JPanel contentArea;
    private javax.swing.JPanel contentArea1;
    private javax.swing.JPanel contentArea2;
    private javax.swing.JPanel contentArea3;
    private javax.swing.JPanel contentArea4;
    private javax.swing.JPanel contentArea5;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField1;
    private javax.swing.JLabel deadLineLabel;
    private javax.swing.JLabel deleteImageLabel;
    private javax.swing.JLabel deleteImageLabel2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel institutionLabel;
    private javax.swing.JTextField institutionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginContent;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuContent;
    private javax.swing.JPanel messageContainer;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel myBooksLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JLabel numberOfBooksLabel;
    private javax.swing.JLabel numberOfBooksLabel1;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel publicationDateLabel;
    private javax.swing.JTextField publicationDateTextField;
    private javax.swing.JLabel publishingCompanyLabel;
    private javax.swing.JTextField publishingCompanyTextField;
    private javax.swing.JLabel recentBooksLabel;
    private javax.swing.JPanel registerBookContent;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    private javax.swing.JPanel registerUserContent;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel searchBarContent;
    private javax.swing.JLabel searchBarLabel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton settingsButton1;
    private javax.swing.JButton settingsButton2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel userContent1;
    private javax.swing.JPanel userContent3;
    private javax.swing.JLabel userImageLabel;
    private javax.swing.JLabel userImageLabel2;
    private javax.swing.JPanel usersContent;
    // End of variables declaration//GEN-END:variables
    
    public JScrollPane getScrollPane() {
        return ScrollPane;
    }

    public void setScrollPane(JScrollPane ScrollPane) {
        this.ScrollPane = ScrollPane;
    }

    public JPanel getBackgroundPanel() {
        return backgroundPanel;
    }

    public void setBackgroundPanel(JPanel backgroundPanel) {
        this.backgroundPanel = backgroundPanel;
    }

    public JLabel getBooksLabel() {
        return booksLabel;
    }

    public void setBooksLabel(JLabel booksLabel) {
        this.booksLabel = booksLabel;
    }

    public JLabel getButtonEsqueciSenha() {
        return buttonEsqueciSenha;
    }

    public void setButtonEsqueciSenha(JLabel buttonEsqueciSenha) {
        this.buttonEsqueciSenha = buttonEsqueciSenha;
    }

    public JLabel getButtonSouBibliotecario() {
        return buttonSouBibliotecario;
    }

    public void setButtonSouBibliotecario(JLabel buttonSouBibliotecario) {
        this.buttonSouBibliotecario = buttonSouBibliotecario;
    }

    public JPanel getCatalogoScreen() {
        return catalogoScreen;
    }

    public void setCatalogoScreen(JPanel catalogoScreen) {
        this.catalogoScreen = catalogoScreen;
    }

    public JPanel getContentArea() {
        return contentArea;
    }

    public void setContentArea(JPanel contentArea) {
        this.contentArea = contentArea;
    }

    public JPanel getContentArea1() {
        return contentArea1;
    }

    public void setContentArea1(JPanel contentArea1) {
        this.contentArea1 = contentArea1;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public void setEmailTextField(JTextField emailTextField) {
        this.emailTextField = emailTextField;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public void setLoginButton(JButton loginButton) {
        this.loginButton = loginButton;
    }

    public JPanel getLoginContent() {
        return loginContent;
    }

    public void setLoginContent(JPanel loginContent) {
        this.loginContent = loginContent;
    }

    public JPanel getLoginScreen() {
        return loginScreen;
    }

    public void setLoginScreen(JPanel loginScreen) {
        this.loginScreen = loginScreen;
    }

    public JLabel getMyBooksLabel() {
        return myBooksLabel;
    }

    public void setMyBooksLabel(JLabel myBooksLabel) {
        this.myBooksLabel = myBooksLabel;
    }

    public JLabel getName1() {
        return name1;
    }

    public void setName1(JLabel name1) {
        this.name1 = name1;
    }

    public JLabel getName2() {
        return name2;
    }

    public void setName2(JLabel name2) {
        this.name2 = name2;
    }

    public JTextField getPasswordTextField() {
        return passwordTextField;
    }

    public void setPasswordTextField(JTextField passwordTextField) {
        this.passwordTextField = passwordTextField;
    }

    public JLabel getRecentBooksLabel() {
        return recentBooksLabel;
    }

    public void setRecentBooksLabel(JLabel recentBooksLabel) {
        this.recentBooksLabel = recentBooksLabel;
    }
}
