/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.syslib;

/**
 *
 * @author engenheiro
 */
public class UsersScreen extends javax.swing.JPanel {

    /**
     * Creates new form UsersScreen
     */
    public UsersScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        searchBarContent = new javax.swing.JPanel();
        backButton = new javax.swing.JLabel();
        searchBarLabel = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        usersContent = new javax.swing.JPanel();
        userContent1 = new javax.swing.JPanel();
        userImageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        numberOfBooksLabel = new javax.swing.JLabel();
        deleteImageLabel = new javax.swing.JLabel();
        userContent2 = new javax.swing.JPanel();
        userImageLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        numberOfBooks1 = new javax.swing.JLabel();
        deleteImageLabel1 = new javax.swing.JLabel();

        name.setBackground(new java.awt.Color(62, 67, 159));
        name.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Syslib");
        name.setToolTipText("");
        name.setOpaque(true);

        backButton.setText("Voltar");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        searchBarLabel.setText("Qual usuário deseja buscar?");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchBarContentLayout = new javax.swing.GroupLayout(searchBarContent);
        searchBarContent.setLayout(searchBarContentLayout);
        searchBarContentLayout.setHorizontalGroup(
            searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBarLabel)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
        );
        searchBarContentLayout.setVerticalGroup(
            searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarContentLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(searchBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchBarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        nameLabel.setText("Daniel Alencar Penha Carvalho");

        numberOfBooksLabel.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        numberOfBooksLabel.setText("18");

        deleteImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N

        javax.swing.GroupLayout userContent1Layout = new javax.swing.GroupLayout(userContent1);
        userContent1.setLayout(userContent1Layout);
        userContent1Layout.setHorizontalGroup(
            userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userContent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(numberOfBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteImageLabel)
                .addGap(12, 12, 12))
        );
        userContent1Layout.setVerticalGroup(
            userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                        .addComponent(userImageLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContent1Layout.createSequentialGroup()
                        .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteImageLabel)
                            .addGroup(userContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameLabel)
                                .addComponent(numberOfBooksLabel)))
                        .addGap(18, 18, 18))))
        );

        userImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        nameLabel1.setText("Maic de Oliveira Santos");

        numberOfBooks1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        numberOfBooks1.setText("18");

        deleteImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N

        javax.swing.GroupLayout userContent2Layout = new javax.swing.GroupLayout(userContent2);
        userContent2.setLayout(userContent2Layout);
        userContent2Layout.setHorizontalGroup(
            userContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userContent2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userImageLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberOfBooks1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteImageLabel1)
                .addGap(12, 12, 12))
        );
        userContent2Layout.setVerticalGroup(
            userContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userContent2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userImageLabel1)
                .addContainerGap())
            .addGroup(userContent2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(userContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteImageLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel1)
                        .addComponent(numberOfBooks1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout usersContentLayout = new javax.swing.GroupLayout(usersContent);
        usersContent.setLayout(usersContentLayout);
        usersContentLayout.setHorizontalGroup(
            usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        usersContentLayout.setVerticalGroup(
            usersContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersContentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(userContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBarContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(usersContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBarContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel deleteImageLabel;
    private javax.swing.JLabel deleteImageLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel numberOfBooks1;
    private javax.swing.JLabel numberOfBooksLabel;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel searchBarContent;
    private javax.swing.JLabel searchBarLabel;
    private javax.swing.JPanel userContent1;
    private javax.swing.JPanel userContent2;
    private javax.swing.JLabel userImageLabel;
    private javax.swing.JLabel userImageLabel1;
    private javax.swing.JPanel usersContent;
    // End of variables declaration//GEN-END:variables
}
